config/routes.rb
Rails.application.routes.draw do
  get  'login',  to: 'sessions#new'
  post 'login',  to: 'sessions#create'
  get  'logout', to: 'sessions#destroy'
  get  'signup', to: 'users#new'
  resources :users
  resources :posts
  root 'static_pages#home'
  get 'static_pages/home'
  get 'static_pages/help'
  get 'static_pages/about'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: { minimum: 3, maximum: 30 }
  validates :body, presence: true, length: { minimum: 5, maximum: 500 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  attr_reader :remember_token
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :name,     presence: true, uniqueness: true, length: { minimum: 3 }
  validates :email,    presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
  validates :password, presence: true, length: { minimum: 6 }
  has_secure_password

  def create_remember_token
    @remember_token = User.new_token
  end

  # Creates and returns the digest of the input
  def User.digest(input)
    # Lower the cost if possible for saving time
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(input)
  end

  # Returns a new random token
  def User.new_token
    SecureRandom.urlsafe_base64 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_login, except: [:show, :index]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      flash[:success] = "New post created."
      redirect_to @post
    else
      flash[:danger] = "Cannot create new post!"
      render 'new'
    end
  end

  def show
    @post = Post.find_by(id: params[:id])
  end
  
  def index
    @posts = Post.all
  end

  private

      def post_params
        params.require(:post).permit(:title, :body)
      end

      # Redirects to home page if user is not logged in
      def require_login
        redirect_to root_url, notice: "You must be logged in for this action." if !logged_in?
      end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    if !logged_in?
      @user = User.new
    else
      flash[:info] = "You are already logged in!"
      redirect_to root_url
    end
  end

  def create
    @user = User.find_by(email: login_params[:email])
    if @user && @user.authenticate(login_params[:password])
      log_in @user
      remember @user if login_params[:remember] == '1'
      flash[:success] = "LOGGED IN"
      redirect_to root_url
    else
      flash[:warning] = "Invalid email or password or even both!"
      render 'new'
    end
  end

  def destroy
    log_out
    flash[:info] = "You have logged out."
    redirect_to root_url
  end

  private

      def login_params
        params.require(:session).permit(:email, :password, :remember)
      end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    redirect_to root_url, notice: "You already have an account!" if logged_in?
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "New account is created!"
      log_in @user
      redirect_to root_url
    else
      flash[:danger] = "Cannot create new user!"
      render 'new'
    end
  end

  private

      def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(title = '')
    base_title = "MembersOnly App"
    return title.empty? ? base_title : "#{title.capitalize} - #{base_title}"
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def formatted_datetime(datetime)
    datetime.getlocal.strftime('%d.%m.%Y - %H:%M')
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:id] = user.id
  end

  # Returns the current logged-in user if any
  def current_user
    if user_id = session[:id]
      @current_user ||= User.find_by(id: user_id)
    elsif user_id = cookies.signed[:user_id]
      @current_user = User.find_by(id: user_id) if authenticated?
    end
  end

  def authenticated?
    if user = User.find_by(id: cookies.signed[:user_id])
      BCrypt::Password.new(user.remember_digest).is_password?(cookies[:remember_token])
    end
  end

  # Returns true if a user is logged in
  def logged_in?
    !current_user.nil?
  end

  def log_out
    session[:id] = nil
    forget
  end

  def remember(user)
    user.create_remember_token
    cookies.permanent[:remember_token] = user.remember_token
    cookies.permanent.signed[:user_id] = user.id
    user.update_attribute(:remember_digest, User.digest(user.remember_token))
  end

  def forget
    cookies.delete(:remember_token)
    cookies.delete(:user_id)
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>
<hr>
<p>Created by JamCry.</p>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">MembersONLY!</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="<%=static_pages_home_url%>">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%=posts_url%>">Posts</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%=static_pages_help_url%>">Help</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%=static_pages_about_url%>">About</a>
      </li>
      <% if logged_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <strong><em><%= current_user.name %></em></strong>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="#">Settings</a>
            <a class="dropdown-item" href="#">My Posts</a>
            <a class="dropdown-item" href="<%= logout_url %>">Log Out</a>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <a class="nav-link" href="<%= login_url %>">Login</a>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield :title) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <%= content_tag :div, value, class: "flash #{key}" %>
    <% end %>
    <%= render "layouts/navbar" %>
    <div class="container">
      <div class="jumbotron"><%= yield %></div>
      <%= render "layouts/footer" %>
    </div>
    
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, placeholder: 'Post Title', class: 'form-control'%>
  </div>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, placeholder: 'Your post here', class: 'form-control'%>
  </div>
  <%= f.submit "Create Post", class: "btn btn-primary" %>
<% end %>

app/views/posts/_posts.html.erb
<div class="card-columns">
  <% @posts = Post.all %>
  <% @posts.each do |post| %>
    <div class="card">
      <div class="card-body">
        <h4 class="card-title"><%= post.title %></h4>
        <h6 class="card-subtitle mb-2 text-muted"><%= formatted_datetime(post.created_at) %></h6>
        <p class="card-text">
          <%= post.body[0..100] + "..." %>
        </p>
        <%= link_to "Read More -->", post , class: 'card-link' %>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/index.html.erb
<% provide(:title, "Posts") %>
<h1>Recent Posts</h1>
<p>
  <% if logged_in? %>
    You are a member, so you can see who wrote what.
  <% else %>
    You are not a member, if you are, <a href="<%= login_url %>">log in</a>.
    Otherwise, you won't be able to see the author of the posts.
  <% end %>
</p>
<%= render 'posts' %>

app/views/posts/new.html.erb
<%= provide(:title, "New Post") %>
<h1>Create a Post</h1>
<div class="row">
  <% if !@post.errors.empty? %>
    <% messages = @post.errors.full_messages %>
    <p>There are <%= pluralize(messages.length,'error') %> in the submitted form: </p>
    <ul class="list-group small">
      <% messages.each do |msg| %>
        <li class="list-group-item list-group-item-danger"><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
</div>
<div class="row">
  <div class="col-md-10 col-md-offset-3 center-form">
    <%= render 'form' %>
  </div>
</div>

app/views/posts/show.html.erb
<% provide(:title, @post.title) %>
<h1>Post <%= @post.id %></h1>
<h2><%= @post.title %></h2>
<p><%= @post.body %></p>
<strong>Author: </strong>
<% if logged_in? %>
  <%= @post.user.name %>
<% else %>
  <em class="text-black-50">(Anonymous)</em>
<% end %>

app/views/shared/_error_messages.html.erb
<% if !@user.errors.empty? %>
  <% messages = @user.errors.full_messages %>
  <p>There are <%= pluralize(messages.length,'error') %> in the submitted form: </p>
  <ul class="list-group small">
    <% messages.each do |msg| %>
      <li class="list-group-item list-group-item-danger"><%= msg %></li>
    <% end %>
  </ul>
<% end %>

app/views/shared/_form.html.erb
<%= form_for(@user) do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, placeholder: 'Username', class:'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, placeholder: 'user@example.com', class:'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, placeholder: 'Minimum 6 characters', class:'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, placeholder: 'Enter password again', class:'form-control' %>
  </div>
  <%= f.submit "Create User", class: "btn btn-primary" %>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>MembersOnly is a private club where the users can write posts about everything. Their name will not
be shown to non-users.</p>
<p>Created by <a href="https://github.com/jamcry"><strong>JamCry</strong></a></p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>This section is still in progress.</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<% provide(:posts, Post.all)%>
<h1>MembersOnly App</h1>
<p>Home page of the app. This app is still in progress.</p>
<% if !logged_in? %>
  <p><strong> You can see the posts, but to see who wrote them: </strong></p>
  <p>
    <a href="<%= login_url %>" class="btn btn-primary">Login</a>
    < or >
    <a href="<%= signup_url %>" class="btn btn-secondary">Signup</a>
  </p>
<% else %>
  <p>Nice to see you <%= current_user.name %>.</p>
<% end %>
<h2>Recent Posts</h2>
<%= render 'posts/posts' %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, placeholder: 'Username', class:'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, placeholder: 'user@example.com', class:'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, placeholder: 'Minimum 6 characters', class:'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, placeholder: 'Enter password again', class:'form-control' %>
  </div>
  <%= f.submit "Create User", class: "btn btn-primary" %>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<% provide(:title, "Signup") %>
<h1>Be a Member Now!</h1>
<p>
  Already a member? <strong><a href="<%= login_url %>">Log in</a></strong> now!
</p>
<div class="row">
  <div class="col-md-6 col-md-offset-3 center-form">
    <%= render 'shared/error_messages' %>
    <%= render 'form'%>
  </div>
</div>